"""Detection Signal 1 — Groq LLM Detector (M3).

Single responsibility: given raw text, return the LLM's assessment of whether
the text is AI-generated or human-written. This module is intentionally
independent of the Flask layer so it can be tested directly.

Spec (do not change the interface):
    groq_classify(text: str) -> dict
    returns: {"score": float in [0, 1], "label": "AI" | "Human"}
    where `score` is the probability that the text is AI-generated.
"""

from __future__ import annotations

import json
import os

from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are an expert text-provenance classifier. Decide whether a passage was "
    "written by a human or generated by an AI language model. Respond with ONLY a "
    "JSON object of the form {\"score\": <float 0..1>, \"label\": \"AI\" | \"Human\"}, "
    "where score is the probability that the text is AI-generated. No prose, no "
    "code fences."
)


def _clamp_unit(value: float) -> float:
    """Clamp a number into the [0.0, 1.0] range."""
    return max(0.0, min(1.0, float(value)))


def _normalize(raw: dict) -> dict:
    """Coerce a model/stub payload into the exact spec shape."""
    score = _clamp_unit(raw.get("score", 0.5))
    label = raw.get("label")
    if label not in ("AI", "Human"):
        # Derive the label from the score if the model omitted/garbled it.
        label = "AI" if score >= 0.5 else "Human"
    return {"score": score, "label": label}


def _stub_classify(text: str) -> dict:
    """Deterministic fallback when no API key / SDK is available.

    Keeps the exact interface so the rest of the pipeline can be built and
    tested offline. This is NOT a real detector — it is a transparent
    placeholder that varies with the input so downstream wiring is observable.
    """
    words = text.split()
    if not words:
        return {"score": 0.5, "label": "Human"}
    # Lexical-diversity heuristic: lower diversity -> more "AI-like".
    diversity = len(set(w.lower() for w in words)) / len(words)
    score = _clamp_unit(1.0 - diversity)
    return _normalize({"score": score, "label": "AI" if score >= 0.5 else "Human"})


def groq_classify(text: str) -> dict:
    """Classify `text` as AI-generated or human-written via the Groq LLM.

    Args:
        text: The raw submitted text.

    Returns:
        {"score": float in [0, 1], "label": "AI" | "Human"} where `score` is the
        probability that the text is AI-generated.

    Falls back to a deterministic stub (same interface) if the Groq SDK or API
    key is unavailable, or if the API call fails.
    """
    if not isinstance(text, str):
        raise TypeError("text must be a str")

    if not GROQ_API_KEY:
        return _stub_classify(text)

    try:
        from groq import Groq  # imported lazily so the stub path needs no SDK

        client = Groq(api_key=GROQ_API_KEY)
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
            response_format={"type": "json_object"},
        )
        payload = json.loads(completion.choices[0].message.content)
        return _normalize(payload)
    except Exception:  # noqa: BLE001 - any failure degrades to the stub
        return _stub_classify(text)


if __name__ == "__main__":
    # Manual smoke test: python groq_detector.py
    samples = [
        "ok",
        "i honestly can't believe this worked lol, took me three tries",
        "The implementation leverages a multi-faceted approach to optimize "
        "throughput while maintaining robust, scalable, and maintainable code.",
    ]
    for s in samples:
        print(repr(s[:40]), "->", groq_classify(s))
