"""Transparency Label Generator (M5).

Converts a combined confidence score into a fixed, user-facing label. The
label text is verbatim from the planning doc — do not paraphrase. Thresholds
are imported from `confidence` so they cannot drift out of sync.

    generate_label(confidence: float) -> str

Bands (must not change):
    confidence >= 0.70        -> Likely AI-generated
    0.40 <= confidence < 0.70 -> Uncertain attribution
    confidence < 0.40         -> Likely human-written
"""

from __future__ import annotations

from confidence import HUMAN_UPPER, UNCERTAIN_UPPER

_LABEL_AI = (
    "Likely AI-generated content.\n"
    "Our analysis indicates strong evidence that this text was generated using "
    "AI systems. This classification is made with high confidence based on "
    "multiple signals."
)

_LABEL_HUMAN = (
    "Likely human-written content.\n"
    "Our analysis indicates strong evidence that this text was written by a "
    "human creator. This classification is made with high confidence based on "
    "multiple signals."
)

_LABEL_UNCERTAIN = (
    "Uncertain attribution.\n"
    "We found mixed or inconclusive signals in this text. We cannot confidently "
    "determine whether it was written by a human or generated by AI. Results are "
    "intentionally conservative to avoid misclassification."
)


def generate_label(confidence: float) -> str:
    """Return the verbatim transparency label for a combined `confidence` score."""
    if confidence >= UNCERTAIN_UPPER:      # >= 0.70
        return _LABEL_AI
    if confidence >= HUMAN_UPPER:          # 0.40 .. 0.69
        return _LABEL_UNCERTAIN
    return _LABEL_HUMAN                     # < 0.40


if __name__ == "__main__":
    for c in (0.10, 0.39, 0.40, 0.69, 0.70, 0.95):
        print(f"--- confidence={c} ---")
        print(generate_label(c))
